Repository TwiN/gatus, pull requests merged in 2022-11, with the labels that each got.

#342 feat(ui): Allow configuring meta description
  README.md
  config/ui/ui.go
  config/ui/ui_test.go
  web/app/public/index.html
Labels: feature

#360 fix: Make sure len([BODY]) works if the body is a JSON array
  core/condition_test.go
  jsonpath/jsonpath.go
  jsonpath/jsonpath_test.go
Labels: bug

#352 feat: support SCTP & UDP as endpoint type
  README.md
  client/client.go
  core/endpoint.go
  core/endpoint_test.go
  go.mod
  go.sum
  vendor/github.com/ishidawataru/sctp/.gitignore
  vendor/github.com/ishidawataru/sctp/.travis.yml
  vendor/github.com/ishidawataru/sctp/GO_LICENSE
  vendor/github.com/ishidawataru/sctp/LICENSE
  vendor/github.com/ishidawataru/sctp/NOTICE
  vendor/github.com/ishidawataru/sctp/README.md
  vendor/github.com/ishidawataru/sctp/ipsock_linux.go
  vendor/github.com/ishidawataru/sctp/sctp.go
  vendor/github.com/ishidawataru/sctp/sctp_linux.go
  vendor/github.com/ishidawataru/sctp/sctp_unsupported.go
  vendor/modules.txt
Labels: feature

#372 fix(jsonpath): Properly handle len of object in array, len of int and len of bool
  core/condition_test.go
  jsonpath/jsonpath.go
  jsonpath/jsonpath_test.go
Labels: bug

#364 fix(alerting): Resolve issue with blank GoogleChat messages
  alerting/alert/alert.go
  alerting/provider/googlechat/googlechat.go
  alerting/provider/googlechat/googlechat_test.go
Labels: bug, alerting
