Repository TwiN/gatus, pull requests merged in 2023-07, with the labels that each got.

#512 feat(alerting): Add token authorization for ntfy
  README.md
  alerting/provider/ntfy/ntfy.go
  alerting/provider/ntfy/ntfy_test.go
Labels: feature, area/alerting

#493 feat(ui): Show number of failing checks per group
  web/app/src/components/EndpointGroup.vue
Labels: feature, area/ui

#531 fix(tls): Pass certificate and private key files to listener method
  README.md
  config/web/web.go
  config/web/web_test.go
  controller/controller.go
Labels: bug
