Repository TwiN/gatus, pull requests merged in 2024-11, with the labels that each got.

#885 docs: Fix typo in README
  README.md
Labels: documentation

#879 feat(pushover): priority on resolved
  README.md
  alerting/provider/pushover/pushover.go
  alerting/provider/pushover/pushover_test.go
Labels: feature, area/alerting

#872 feat(logging): Allow configuring logging verbosity level
  README.md
  config/config.go
  go.mod
  go.sum
  main.go
  watchdog/watchdog.go
Labels: feature

#895 fix(logging): Replace log-level parameter by GATUS_LOG_LEVEL env var
  .examples/docker-compose-multiple-config-files/config/global.yaml
  .github/workflows/benchmark.yml
  .github/workflows/test.yml
  Dockerfile
  README.md
  alerting/config.go
  alerting/provider/pagerduty/pagerduty.go
  api/api.go
  api/chart.go
  api/endpoint_status.go
  api/external_endpoint.go
  api/spa.go
  client/client.go
  client/config.go
  config/config.go
  config/config_test.go
  config/endpoint/condition.go
  config/remote/remote.go
  controller/controller.go
  go.mod
  go.sum
  main.go
  security/config.go
  security/oidc.go
  storage/store/sql/sql.go
  storage/store/store.go
  watchdog/alerting.go
  watchdog/alerting_test.go
  watchdog/watchdog.go
Labels: bug

#903 feat(alerting): Update Adaptive Cards design for teams-workflows
  alerting/provider/teamsworkflows/teamsworkflows.go
  alerting/provider/teamsworkflows/teamsworkflows_test.go
Labels: feature, area/alerting

#886 feat(client): Add support for PTR DNS records
  client/client.go
  client/client_test.go
Labels: feature
