Repository TwiN/gatus, pull requests merged in 2024-02, with the labels that each got.

#652 feat: shields.io endpoint badge
  README.md
  api/api.go
  api/badge.go
  api/badge_test.go
Labels: feature

#661 feat(client): Add client network configuration for ICMP endpoint clients
  README.md
  client/client.go
  client/client_test.go
  client/config.go
Labels: feature

#675 fix(web): Allow configuration of read-buffer-size
  README.md
  api/api.go
  config/web/web.go
  config/web/web_test.go
Labels: bug, area/networking

#676 refactor(alerting): Use pointer for receiver in AlertProvider.GetDefaultAlert method
  alerting/provider/awsses/awsses.go
  alerting/provider/awsses/awsses_test.go
  alerting/provider/custom/custom.go
  alerting/provider/custom/custom_test.go
  alerting/provider/discord/discord.go
  alerting/provider/discord/discord_test.go
  alerting/provider/email/email.go
  alerting/provider/email/email_test.go
  alerting/provider/github/github.go
  alerting/provider/github/github_test.go
  alerting/provider/gitlab/gitlab.go
  alerting/provider/gitlab/gitlab_test.go
  alerting/provider/googlechat/googlechat.go
  alerting/provider/googlechat/googlechat_test.go
  alerting/provider/gotify/gotify.go
  alerting/provider/matrix/matrix.go
  alerting/provider/matrix/matrix_test.go
  alerting/provider/mattermost/mattermost.go
  alerting/provider/mattermost/mattermost_test.go
  alerting/provider/messagebird/messagebird.go
  alerting/provider/messagebird/messagebird_test.go
  alerting/provider/ntfy/ntfy.go
  alerting/provider/opsgenie/opsgenie.go
  alerting/provider/pagerduty/pagerduty.go
  alerting/provider/pagerduty/pagerduty_test.go
  alerting/provider/pushover/pushover.go
  alerting/provider/pushover/pushover_test.go
  alerting/provider/slack/slack.go
  alerting/provider/slack/slack_test.go
  alerting/provider/teams/teams.go
  alerting/provider/teams/teams_test.go
  alerting/provider/telegram/telegram.go
  alerting/provider/telegram/telegram_test.go
  alerting/provider/twilio/twilio.go
  alerting/provider/twilio/twilio_test.go
Labels: area/alerting

#668 feat(http): enhance HTTP client configuration with proxy support
  README.md
  client/config.go
  client/config_test.go
Labels: feature, area/networking
