Repository TwiN/gatus, pull requests merged in 2025-08, with the labels that each got.

#1180 feat(websocket): add support for custom headers in WS check
  README.md
  client/client.go
  client/client_test.go
  config/endpoint/endpoint.go
Labels: feature

#979 feat(metrics): add support for custom labels in Prometheus metrics
  README.md
  api/external_endpoint.go
  config/config.go
  config/config_test.go
  config/endpoint/endpoint.go
  config/util.go
  main.go
  metrics/metrics.go
  metrics/metrics_test.go
  watchdog/watchdog.go
Labels: feature, area/metrics

#1138 feat(alerting): Implement alert reminders
  README.md
  alerting/alert/alert.go
  alerting/provider/ilert/ilert_test.go
  config/endpoint/endpoint.go
  watchdog/alerting.go
  watchdog/alerting_test.go
Labels: feature, area/alerting

#1189 docs: Add section for gatus-sdk
  README.md
Labels: documentation

#1194 docs: tweak `minimum-reminder-interval` description
  README.md
Labels: documentation

#1202 fix(ui): Replace filter value "nothing" by "none"
  README.md
  config/ui/ui.go
  config/ui/ui_test.go
  web/app/src/components/SearchBar.vue
  web/static/js/app.js
Labels: bug, area/ui

#1204 feat: Implement announcements
  README.md
  api/api.go
  api/config.go
  api/config_test.go
  config/announcement/announcement.go
  config/config.go
  web/app/src/App.vue
  web/app/src/components/AnnouncementBanner.vue
  web/app/src/views/Home.vue
  web/static/css/app.css
  web/static/js/app.js
  web/static/js/chunk-vendors.js
Labels: feature, area/ui

#1212 fix(ui): Collapse groups by default
  web/app/src/views/Home.vue
  web/static/js/app.js
Labels: bug, area/ui

#1220 docs: Fix typo in Zulip configuration section
  README.md
Labels: documentation, area/alerting
