Repository TwiN/gatus, pull requests merged in 2025-02, with the labels that each got.

#990 fix(remote): Support partial remote instance failure
  api/endpoint_status.go
Labels: bug

#972 feat(alerting): Add Incident.io alerting provider
  README.md
  alerting/alert/type.go
  alerting/config.go
  alerting/provider/incidentio/incident_io.go
  alerting/provider/incidentio/incident_io_test.go
  alerting/provider/provider.go
  config/config.go
Labels: feature, area/alerting

#998 ci: Add workflow to test UI changes
  .github/workflows/test-ui.yml
  Makefile
Labels: area/ui

#994 feat(ui): expose 30d badges and response chart selector for duration
  README.md
  api/raw.go
  web/app/src/views/Details.vue
  web/static/css/app.css
  web/static/js/app.js
  web/static/js/chunk-vendors.js
Labels: feature, area/ui

#1002 fix(ui): Don't override body/html background-color
  web/app/src/index.css
  web/static/css/app.css
Labels: bug, area/ui

#982 feat(maintenance): Per-endpoint maintenance configuration
  README.md
  config/endpoint/endpoint.go
  config/endpoint/endpoint_test.go
  watchdog/watchdog.go
Labels: feature

#1005 feat(dns): Support SRV query type
  client/client.go
Labels: feature, area/client
