Repository TwiN/gatus, pull requests merged in 2025-01, with the labels that each got.

#954 ci: Add image labels, merge publish to Docker Hub/GHCR workflows
  .github/workflows/publish-experimental.yml
  .github/workflows/publish-latest-to-ghcr.yml
  .github/workflows/publish-latest.yml
  .github/workflows/publish-release-to-ghcr.yml
  .github/workflows/publish-release.yml
Labels: feature

#941 fix(alerting): replace HTML entities with emojis in teams-workflows provider to prevent rendering issues
  alerting/provider/teamsworkflows/teamsworkflows.go
  alerting/provider/teamsworkflows/teamsworkflows_test.go
Labels: area/alerting

#968 test: Fix flaky DNS tests that check for valid IP
  client/client_test.go
  config/endpoint/endpoint_test.go
Labels: bug
