Repository TwiN/gatus, pull requests merged in 2025-03, with the labels that each got.

#1017 docs: Clarify that disable-monitoring-lock is akin to enabling parallel execution
  README.md
Labels: documentation

#1015 feat(ui): Allow configuring default dark-mode value
  README.md
  api/spa.go
  api/spa_test.go
  config/ui/ui.go
  web/app/public/index.html
  web/app/src/App.vue
  web/app/src/components/Settings.vue
  web/static/index.html
  web/static/js/app.js
Labels: bug, feature, area/ui

#1034 fix(alerting): Ensure that alerting.incident-io.url has the correct prefix
  README.md
  alerting/provider/incidentio/incidentio.go
  alerting/provider/incidentio/incidentio_test.go
Labels: bug, area/alerting

#1038 feat(ui): Implement ability to hide port from endpoint results via `endpoints[].ui.hide-port`
  README.md
  config/endpoint/endpoint.go
  config/endpoint/endpoint_test.go
  config/endpoint/result.go
  config/endpoint/ui/ui.go
Labels: feature, area/ui, area/security

#1043 fix(client): Correctly parse hostname for ICMP endpoint when using IPv6
  config/endpoint/endpoint.go
Labels: bug, area/client

#1047 fix(ci,deps): Bump Go version to 1.24.1 and update some dependencies
  .github/workflows/benchmark.yml
  .github/workflows/test.yml
  go.mod
  go.sum
Labels: bug, dependencies
