Repository TwiN/gatus, pull requests merged in 2025-07, with the labels that each got.

#1149 fix: Limit the pageSize to maximum-number-of-results on first page
  api/util.go
Labels: bug

#1150 fix: Convert key to lowercase when looking up endpoint by key
  config/config.go
Labels: bug

#928 feat(alerting): Support sending messages to Telegram topics in group
  README.md
  alerting/provider/telegram/telegram.go
  alerting/provider/telegram/telegram_test.go
Labels: feature, area/alerting

#1134 feat: Add body to TCP, UDP, and TLS endpoints and templating
  README.md
  client/client.go
  client/client_test.go
  config/connectivity/connectivity.go
  config/endpoint/endpoint.go
Labels: feature, area/networking, area/client

#1165 fix(WebSocket): use tls config
  client/client.go
Labels: bug

#1173 feat(external-endpoint): Implement heartbeat
  README.md
  api/external_endpoint.go
  config/endpoint/external_endpoint.go
  config/endpoint/heartbeat/heartbeat.go
  storage/store/memory/memory.go
  storage/store/memory/memory_test.go
  storage/store/sql/sql.go
  storage/store/sql/sql_test.go
  storage/store/store.go
  watchdog/watchdog.go
Labels: feature
